const USERS = [
  {
    key: 1,
    id: 1,
    status: "pending",
    title: "Job 1",
    type: "Full-time",
    company: "Company 1",
    description: "Job 1 description",
    dateadded: new Date("2023-06-18"),
    deadline: new Date("2023-06-30"),
    location: "Location 1",
    creatorId: "user",
  },
  {
    key: 1,
    id: 2,
    status: "pending",
    title: "Job 1",
    type: "Part-Time",
    company: "Company 1",
    description: "Job 1 description",
    dateadded: new Date("2023-06-18"),
    deadline: new Date("2023-06-30"),
    location: "Location 1",
    creatorId: "user",
  },
  {
    key: 1,
    id: 3,
    status: "accepted",
    title: "Job 1",
    type: "Full-time",
    company: "Company 1",
    description: "Job 1 description",
    dateadded: new Date("2023-06-18"),
    deadline: new Date("2023-06-30"),
    location: "Location 1",
    creatorId: "user",
  },
  {
    key: 1,
    id: 4,
    status: "rejected",
    title: "Job 1",
    type: "Full-time",
    company: "Company 1",
    description: "Job 1 description",
    dateadded: new Date("2023-06-18"),
    deadline: new Date("2023-06-30"),
    location: "Location 1",
    creatorId: "user",
  },
  {
    key: 1,
    id: 5,
    status: "pending",
    title: "Job 1",
    type: "Full-time",
    company: "Company 1",
    description: "Job 1 description",
    dateadded: new Date("2023-06-18"),
    deadline: new Date("2023-06-30"),
    location: "Location 1",
    creatorId: "user",
  },
  {
    key: 1,
    id: 6,
    status: "pending",
    title: "Job 1",
    type: "Full-time",
    company: "Company 1",
    description: "Job 1 description",
    dateadded: new Date("2023-06-18"),
    deadline: new Date("2023-06-30"),
    location: "Location 1",
    places: "user",
    creatorId: "user",
  },
];

export default USERS;
